#!/bin/sh
set -eu

: "${DB_PASSWORD:?DB_PASSWORD is required}"
: "${DB_APP_PASSWORD:?DB_APP_PASSWORD is required}"
DB_APP_USER="${DB_APP_USER:-stgp_app}"

case "$DB_APP_USER" in
  ''|*[!A-Za-z0-9_]*)
    echo "DB_APP_USER must contain only letters, numbers, and underscores" >&2
    exit 1
    ;;
esac

APP_PASSWORD_SQL=$(printf "%s" "$DB_APP_PASSWORD" | sed "s/'/''/g")
export PGPASSWORD="$DB_PASSWORD"

psql -h postgres -U postgres -d stgp_prod -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB_APP_USER') THEN
    CREATE ROLE "$DB_APP_USER" LOGIN PASSWORD '$APP_PASSWORD_SQL';
  ELSE
    ALTER ROLE "$DB_APP_USER" LOGIN PASSWORD '$APP_PASSWORD_SQL';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE stgp_prod TO "$DB_APP_USER";
GRANT USAGE ON SCHEMA public TO "$DB_APP_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$DB_APP_USER";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "$DB_APP_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$DB_APP_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$DB_APP_USER";
SQL
